const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const envPath = path.join(root, ".env");
const outputPath = path.join(root, "src", "pkjs", "generated-config.js");

const env = Object.assign({}, parseEnvFile(envPath), process.env);
const clientId = env.ECOBEE_CLIENT_ID || "ABC123";

fs.writeFileSync(
  outputPath,
  [
    "// Generated by scripts/generate-config.js. Do not edit.",
    "module.exports = {",
    `	ECOBEE_CLIENT_ID: ${JSON.stringify(clientId)}`,
    "};",
    "",
  ].join("\n")
);

if (!env.ECOBEE_CLIENT_ID) {
  console.warn("ECOBEE_CLIENT_ID is not set; using placeholder ABC123.");
}

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};

  return fs
    .readFileSync(filePath, "utf8")
    .split(/\r?\n/)
    .reduce((values, line) => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) return values;

      const separator = trimmed.indexOf("=");
      if (separator === -1) return values;

      const key = trimmed.slice(0, separator).trim();
      const value = trimmed.slice(separator + 1).trim();
      values[key] = unquote(value);
      return values;
    }, {});
}

function unquote(value) {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }
  return value;
}
